### PR TITLE
Add missing currentColor keyword

### PR DESCRIPTION
**Pull request by gouch**
This is a valid <color> value that was missing

### CODE REVIEW

**Comment by tgfjt** [comment]
Inserting, It seems should be an alphabetical order:D

**Comment by gouch** [comment]
I'd appreciate this being merged or at least getting some feedback. It's a straightforward bug fix, it passes the tests, and it will resolve issue [#590](https://github.com/CSSLint/csslint/issues/590) with CSSLint.

**Comment by gamebox** [comment]
Why was this not merged?  The issue is still open and it is mildly annoying.

**Comment by XhmikosR** [comment]
@gouch: please fetch, rebase and squash the patches. While at it, use a simple single quote instead of the curly ones.

**Comment by frvge** [comment]
@gouch Please add it at the location in the right alphabetical order.

**Comment by gouch** [comment]
@XhmikosR Done

@frvge Colors.js is organized like the [CSS spec](http://www.w3.org/TR/css3-color/#currentcolor), and I did the same.

**Comment by XhmikosR** [comment]
Please squash the commits into one since they refer to the same thing.

**Comment by gouch** [comment]
@XhmikosR Should be one commit now

**Comment by XhmikosR** [comment]
@gouch: almost there :/ You need to fetch upstream and rebase.

**Comment by gouch** [comment]
Continued in new pull request: #177 
(Couldn't figure out how to "fetch upstream and rebase" while maintaining a single commit)

**Pull request closed without merging**
