### PR TITLE
Adding fill because it is a valid css attribute.

### PR DESCRIPTION
**Pull request by lukasoppermann**

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Is this going to be merged and released soon?

**Comment by cscott** [comment]
@XhmikosR this patch can be directly merged.  I've tested it, seems fine.

**Comment by XhmikosR** [comment]
@stubbornella @nschonni: might be worth giving @cscott push rights.

**Comment by stubbornella** [comment]
Done

**Comment by XhmikosR** [comment]
Hmm, I don't see him listed but maybe it's because he didn't accept the email yet. ping @cscott

**Comment by cscott** [comment]
Thanks, @XhmikosR and @stubbornella.  You're right, it was buried in my inbox.  But I found it!

I'm going to continue to push PRs for now, to ensure the patches get reviewed by someone other than myself before being merged.

**Pull request merged**
