### PR TITLE
fill, stroke, opacity properties

### PR DESCRIPTION
**Pull request by ovanderzee**
Fill and stroke are the svg properties with probably the most use cases, since they can paint inline svg icons.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ovanderzee: can you squash those into one patch?

**Comment by ovanderzee** [comment]
In the same branch or on the master?

2016-01-15 8:40 GMT+01:00 XhmikosR <notifications@github.com>:

> @ovanderzee <https://github.com/ovanderzee>: can you squash those into
> one patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSSLint/parser-lib/pull/162#issuecomment-171894013>.
>



-- 
*Onno van der Zee*
Front-end developer
_______________________

*iPROFS*
Coengebouw
Kabelweg 37
1014 BA Amsterdam
T 085 - 044 47 00
I  www.iprofs.nl
_______________________

*iPROFS, waar IT geen doel op zich is*

**Comment by XhmikosR** [comment]
```
git fetch upstream/master
git rebase -i upstream/master
```

**Comment by frvge** [comment]
@ovanderzee Please rebase -i

**Comment by cscott** [comment]
Rebased and squashed in PR #195.

**Pull request closed without merging**
