### PR TITLE
fixes #170: allowing a value of "radio" for the appearance property

### LINKED ISSUE #170: Allow for "appearance" value "radio"
The [official draft spec](https://drafts.csswg.org/css-ui-4/#appearance-switching) seems to be heading in the direction of only allowing `auto` and `none` as possible values for the `appearance` property. However, [at least Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance) supports a value of `radio`, and [this article](https://css-tricks.com/almanac/properties/a/appearance/) implies that Webkit does as well.

### PR DESCRIPTION
**Pull request by dlockhart**

### CODE REVIEW

**Comment by frvge** [comment]
The appearance property has been dropped as you already stated in your other PR. ( https://wiki.csswg.org/spec/css4-ui#dropped-css3-features ) but work is underway for a new one ( https://drafts.csswg.org/css-ui-4/#propdef-appearance ) It seems like only Firefox has implemented "radio-button" but sources disagree.

There are bigger lists of appearance values. For example https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance . In this one "radio-button" isn't listed.

I think we should add everything we can find, or nothing. Looking for more feedback.

Please also rebase.

**Comment by dlockhart** [comment]
`radio-button` isn't actually the problem here -- it was already listed as an acceptable value before this change. `radio` is the value that I added, which is listed in the Mozilla documentation.

**Comment by frvge** [comment]
Ok, true, but the other point remains. Requesting more feedback from others. please rebase.

**Comment by mattiacci** [comment]
Adding the other values seems reasonable, but I see no reason to wait for those additions to merge this.

**Comment by frvge** [comment]
Ok, we can merge this one then after the rebase. I'll see if I can spend a bit of time next week on going through the various documentations and then trying to make the list as long as possible. Then hopefully we'll cover all.

**Comment by XhmikosR** [comment]
I'm baffled with all this because it's not a standard yet. That being said, we should add all of the current properties.

**Comment by stubbornella** [comment]
We made a decision some time ago to give preference to how actual browsers behave and CSS devs author over exactly what is standardized. Eg the IE property hacks. Nick wanted to blow up if we saw one, but they were still heavily used at that point. We needed to support the behavior.

**Comment by XhmikosR** [comment]
@stubbornella: please remove that annoying rebase thing from the repository's settings.

**Comment by nschonni** [comment]
@XhmikosR status check is removed

**Comment by XhmikosR** [comment]
@nschonni: thanks!

**Pull request merged**
