### PR TITLE
Add support for position: -webkit-sticky

### PR DESCRIPTION
**Pull request by toptalo**
- add `-webkit-sticky` to availible positions list
- add `.idea/` folder to `.gitignore` for WebStorm
- rebuild package

### CODE REVIEW

**Comment by stubbornella** [comment]
Please separate your stylistic changes into a different PR and resubmit it.

**Comment by toptalo** [comment]
Is this okay or it will be better to close this PR and make another one for more clean history?
With only one change

**Comment by stubbornella** [comment]
It's fine, what do you think about adding a CSS validation test? Like maybe in this file: https://github.com/CSSLint/parser-lib/blob/0263b2dcf5156ba7fd817e46d567a1917b776b03/tests/css/Validation.js#L1551

**Comment by toptalo** [comment]
Added validation test

**Comment by toptalo** [comment]
Thanks!

**Comment by toptalo** [comment]
Hello @stubbornella,
maybe you'll have time to see my other PR (#237, #238, #239)

**Pull request merged**
