### PR TITLE
[Fix #131] Add support for the 'fr' unit

### LINKED ISSUE #131: Add support for the 'fr' unit
The `fr` unit is part of the [CSS Grid spec](http://www.w3.org/TR/css3-grid-layout/#fr-unit).

Currently, the parser fails to parse rules that use the 'fr' unit.

Here's an example usage:
```css
.my-grid {
  display: -ms-grid;
  -ms-grid-columns: auto 1fr;
}
```

### PR DESCRIPTION
**Pull request by kkirsche**
[Fix #131] Add support for the `fr` unit

cc: @nschonni

### CODE REVIEW

**Comment by kkirsche** [comment]
Wanted to follow up and see if there was anything this was missing.

**Comment by kkirsche** [comment]
Wanted to follow up and see if there was anything this was missing.

**Comment by kkirsche** [comment]
Wanted to follow up on this as I haven't heard a response about this PR yet. Thanks!

**Comment by kkirsche** [comment]
Wanted to follow up on this as I haven't heard a response about this PR yet. Thanks!

**Comment by kkirsche** [comment]
Wanted to follow up on this as I haven't heard a response about this PR yet. Thanks!

**Comment by genexp** [comment]
+1

**Pull request merged**
