### PR TITLE
Add manipulation value for the touch-action property.

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Added `manipulation` value for the `touch-action` property. References: [[1](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)] [[2](https://msdn.microsoft.com/en-gb/library/windows/apps/hh767313.aspx)]

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
@nschonni ping on this PR.

**Comment by XhmikosR** [comment]
@AurelioDeRosa: please fetch, rebase and squash the patches.

**Comment by AurelioDeRosa** [comment]
The branch is now made of only 1 commit and master can be merged with a fast forward only method.

**Comment by XhmikosR** [comment]
Thanks! Before merging it I see that there are more possible values from MSDN https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action.

Maybe you should add those too?

**Comment by XhmikosR** [comment]
@stubbornella: can you remove whatever you have added to the repo that forces merging from master? It's annoying and it blocks PRs that don't need any rebase/merging.

I'd also remove the master branch CI integration because it doesn't allow one to update the docs without skipping CI.

**Comment by AurelioDeRosa** [comment]
Updated.

**Comment by XhmikosR** [comment]
Unfortunately @AurelioDeRosa you need to fetch and rebase because of that repo setting.

**Comment by AurelioDeRosa** [comment]
I've to say that this is a quite cumbersome and tedious process. Especially for small contributions this might really block people from contributing. In jQuery we usually perform these small rebases and tweaks by ourselves, and I think it saves time.

**Comment by XhmikosR** [comment]
IMO this thing shouldn't exist. It's just useless. That is why I pinged @stubbornella above https://github.com/CSSLint/parser-lib/pull/154#issuecomment-170240950

I can't change this myself; only repo owners.

**Comment by stubbornella** [comment]
Is this a Github setting do you think?

**Comment by XhmikosR** [comment]
@stubbornella: yeah, it's in repo settings, branches. Protected branches.

**Comment by jawshooah** [comment]
Note that you can leave `master` as a protected branch (disabling force-pushes) but remove required status checks.

**Pull request merged**
